name: github_search_app
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: 3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #General
  injectable: 2.3.0
  get_it: 7.6.2
  fimber_io: 0.7.0
  auto_route: 7.8.3
  freezed: 2.4.1
  mockito: 5.4.2
  webview_flutter: 4.2.4
  provider: 6.0.5

  #Https
  dio: 5.3.2
  retrofit: 4.0.1
  internet_connection_checker: 1.0.0+1
  json_serializable: 6.7.1
  pretty_dio_logger: 1.3.1

  #Bloc
  flutter_bloc: 8.1.3
  hooked_bloc: 1.4.2
  bloc_test: 9.1.4

  #DB
  hive: 2.2.3
  hive_flutter: 1.1.0

  #Utils
  flutter_device_type: 0.4.0
  intl: 0.18.1
  flutter_hooks: 0.18.6

  #UI
  flutter_screenutil: 5.9.0
  cupertino_icons: 1.0.2
  easy_debounce: 2.0.3
  octo_image: 1.0.2
  cached_network_image: 3.2.3
  flutter_svg: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.4.6
  injectable_generator: 2.4.0
  auto_route_generator: 7.3.1
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  retrofit_generator: 7.0.8
  flutter_gen_runner: 5.3.2
  hive_generator: 2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en

flutter_gen:
  output: lib/generated/assets/
  integrations:
    flutter_svg: true
